language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../mp2-lab1-matrix
  - make -j
  - cd ./bin/
  - ./test_matrix --gtest_list_tests
notifications:
  email: false
